### PR TITLE
Julia 07 compat

### PR DESCRIPTION
**Pull request by gdkrmr**

### CODE REVIEW

**Comment by gdkrmr** [comment]
#60 , there are still tons of warnings, but tests pass.

**Comment by gdkrmr** [comment]
I took care of the deprecation warning that did not require any thought.

**Comment by gdkrmr** [comment]
no more warnings and while I was at it I also changed all the `@info` macros to `@testset`

**Comment by trthatcher** [comment]
Hey! Thanks for going through that - lot's of tedious changes for `0.7`.

I've found myself crazy busy - sorry for leaving you hanging for a few days.

**Comment by gdkrmr** [comment]
don't worry, it passes all the tests now, I have not tested it in real life yet.

**Pull request merged**
